kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: azdisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: azuredisk
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: jenkins-1
spec:
  replicas: 1
  template:
    metadata:
      name: jenkins-1
      labels:
        app: jenkins-1
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k8s-agent-309f2876-1
      containers:
      - name: jenkins-container
        image: zackliu1995/jenkins
        volumeMounts:
        - name: azure
          mountPath: /var/jenkins_home
        securityContext:
          privileged: true
        ports:
          - name: port8080
            containerPort: 8080
            protocol: TCP
          - name: port50000
            containerPort: 50000
            protocol: TCP
          - name: port22
            containerPort: 22
      volumes:
        - name: azure
          persistentVolumeClaim:
            claimName: azdisk
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: jenkins-srv
# spec:
#   selector:
#     app: jenkins-1
#   ports:
#     - name: http
#       port: 80
#       protocol: TCP
#       targetPort: 8080
#     - name: slave
#       port: 50000
#       protocol: TCP
#       targetPort: 50000
#     - name: ssh
#       port: 22
#       targetPort: 22
#   type: LoadBalancer
