kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: jenkins-t
spec:
  replicas: 1
  template:
    metadata:
      name: jenkins-t
      labels:
        app: jenkins-t
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k8s-agent-309f2876-0
      containers:
      - name: jenkins-container
        image: jenkins
        ports:
          - name: port8080
            containerPort: 8080
          - name: port50000
            containerPort: 50000
          - name: port22
            containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-srv-t
spec:
  selector:
    app: jenkins-t
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: slave
      port: 50000
      targetPort: 50000
    - name: ssh
      port: 22
      targetPort: 22
  type: LoadBalancer
    

  
